import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/templates/header/Header'
import Footer from '@/components/templates/footer/Footer'
import { getServerSession } from 'next-auth'
import SessionProvider from '@/components/SessionProvider'
import ProviderStore from '@/modules/redux/provider'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Medusa Store',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession()
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <SessionProvider session={session}>
          <ProviderStore>
            <Header />
            {children}
            <Footer />
          </ProviderStore>
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  )
}
